name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  update-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: "S3 Bucket sync"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "s3://orcavo.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
